name: Run API Tests on Push

on:
  push:
    branches: [ "main", "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4
        with:
          maven-version: '3.9.3'

      - name: Run Tests
        run: mvn clean test

      - name: Archive TestNG Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: testng-results
          path: test-output/
